### ISSUE TITLE
Coffeescript support?

### ISSUE THREAD

**Issue by JorritPosthuma** [jasperkuperus/ionic-quickstart#1]
Hi!

Really love your work so far! Do you think it would be easy to add CoffeeScript support?

Thank in advance!

**Comment by jasperkuperus** [comment]
Hi! Thanks!

The purpose of this project is to have a lean and clean starting point for an ionic project, using gulp. Therefore, I will not be adding things like CoffeeScript out of the box.

However, because of gulp, it is fairly easy to implement something like CoffeeScript. For the purpose of demonstration, check this branch out which fully supports Coffeescript (+sourcemaps):

https://github.com/jasperkuperus/ionic-quickstart/compare/coffeescript

Primarily look at `gulp-config.js` and `gulpfile.js`. The rest is just a `.js` > `.coffee` rewrite.
